# Generated by Django 5.2.10 on 2026-03-06 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "channex_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Channex ID",
                    ),
                ),
                (
                    "property_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Property ID"
                    ),
                ),
                (
                    "property_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Property Name"
                    ),
                ),
                (
                    "ota_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="OTA Name",
                    ),
                ),
                (
                    "reservation_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reservation ID"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Review Content"),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Overall Score"
                    ),
                ),
                (
                    "has_reply",
                    models.BooleanField(default=False, verbose_name="Has Reply"),
                ),
                ("reply", models.TextField(blank=True, verbose_name="Owner Reply")),
                (
                    "is_pending",
                    models.BooleanField(default=False, verbose_name="Is Pending"),
                ),
                ("scores", models.JSONField(default=list, verbose_name="Scores")),
                ("tags", models.JSONField(default=list, verbose_name="Tags")),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                ("raw_data", models.JSONField(default=dict, verbose_name="Raw Data")),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-reviewed_at", "-created_at"],
            },
        ),
    ]
