# Generated by Django 5.2.10 on 2026-04-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="location",
            field=models.CharField(blank=True, max_length=512, verbose_name="Location"),
        ),
    ]
