# Generated by Django 5.2.10 on 2026-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_add_location_to_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Reviewer Name"
            ),
        ),
    ]
