# Generated by Django 5.2.10 on 2026-04-25 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_add_reviewer_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "ota",
                    models.CharField(
                        choices=[("Booking.com", "Booking.com")],
                        default="Booking.com",
                        max_length=32,
                        verbose_name="OTA",
                    ),
                ),
                (
                    "booking_hotel_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="Booking.com Hotel ID",
                    ),
                ),
                (
                    "property_name",
                    models.CharField(max_length=255, verbose_name="Property Name"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Location"
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Synced At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["property_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "ota", "booking_hotel_id"),
                        name="unique_property_per_user_ota",
                    )
                ],
            },
        ),
    ]
