# Generated by Django 5.2.10 on 2026-04-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="currency",
            field=models.CharField(blank=True, max_length=8, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude"),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude"),
        ),
    ]
