# Generated by Django 5.2.10 on 2026-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_property_currency_property_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="expedia_property_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                verbose_name="Expedia/Hotels.com Property ID",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="booking_hotel_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                verbose_name="Booking.com Hotel ID",
            ),
        ),
    ]
