# Generated by Django 5.2.10 on 2026-04-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_property_expedia_property_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="google_place_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Google Place ID",
            ),
        ),
    ]
