# Generated by Django 5.2.10 on 2026-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_property_google_place_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["property_name", "ota_name", "reviewed_at"],
                name="reviews_rev_propert_395ac7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["property_id", "ota_name"],
                name="reviews_rev_propert_10ac5d_idx",
            ),
        ),
    ]
