# Generated by Django 5.2.10 on 2026-07-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_review_reviews_rev_propert_395ac7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(blank=True, max_length=64, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="review",
            name="reply_detected_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reply Detected At"
            ),
        ),
    ]
