# Generated by Django 5.2.10 on 2026-07-13 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_property_country_review_reply_detected_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("snapshot_date", models.DateField(verbose_name="Snapshot Date")),
                ("checkin", models.DateField(verbose_name="Check-in Date")),
                (
                    "user_rate",
                    models.FloatField(blank=True, null=True, verbose_name="User Rate"),
                ),
                (
                    "comp_avg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Comp-set Average"
                    ),
                ),
                (
                    "comp_count",
                    models.IntegerField(default=0, verbose_name="Competitors Counted"),
                ),
                (
                    "currency",
                    models.CharField(blank=True, max_length=8, verbose_name="Currency"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_snapshots",
                        to="reviews.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Snapshot",
                "verbose_name_plural": "Rate Snapshots",
                "ordering": ["-snapshot_date", "checkin"],
                "indexes": [
                    models.Index(
                        fields=["property", "checkin"],
                        name="reviews_rat_propert_b09b85_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("property", "snapshot_date", "checkin"),
                        name="unique_rate_snapshot_per_day",
                    )
                ],
            },
        ),
    ]
