# Generated by Django 5.2.10 on 2026-07-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_ratesnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="draft_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Draft Generated At"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="draft_reply",
            field=models.TextField(blank=True, verbose_name="AI Draft Reply"),
        ),
    ]
