# Generated by Django 5.2.10 on 2026-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_review_draft_generated_at_review_draft_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="handled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Marked Handled At"
            ),
        ),
    ]
