#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# we don't want to run this prior to migration since celery tables will not be available
wait-for-it -s django:5000 -t 600 -- echo "django is up"

exec celery -A config.celery_app beat -l INFO
