// This file is auto-generated by openapi-typescript
// Run: npm run generate-api

export interface paths {
  // API paths will be generated here
}

export interface components {
  schemas: {
    // Schema types will be generated here
  }
}
