# Generated by Django 5.2.10 on 2026-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_customer_apikey_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=512, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=128, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Company / Hotel group"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=128, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=64, verbose_name="Phone"),
        ),
    ]
