# Generated by Django 5.2.10 on 2026-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferences",
            name="alert_email",
            field=models.EmailField(
                blank=True,
                help_text="Send alerts to this address instead of the account email.",
                max_length=254,
                verbose_name="Alert email override",
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="notify_daily_digest",
            field=models.BooleanField(default=False, verbose_name="Daily digest"),
        ),
        migrations.AddField(
            model_name="preferences",
            name="notify_negative_reviews",
            field=models.BooleanField(
                default=True, verbose_name="Instant alert on negative reviews"
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="notify_new_reviews",
            field=models.BooleanField(
                default=True, verbose_name="Email on new reviews"
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="notify_rate_changes",
            field=models.BooleanField(
                default=True, verbose_name="Rate movement alerts"
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="notify_sync_failures",
            field=models.BooleanField(default=True, verbose_name="Sync failure alerts"),
        ),
        migrations.AddField(
            model_name="preferences",
            name="notify_weekly_summary",
            field=models.BooleanField(default=True, verbose_name="Weekly summary"),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="receive_marketing_emails",
            field=models.BooleanField(
                default=False,
                help_text="Receive emails about promotions.",
                verbose_name="Receive Marketing Emails",
            ),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="receive_product_update_emails",
            field=models.BooleanField(
                default=False,
                help_text="Receive emails when we add new features.",
                verbose_name="Receive Product Update Emails",
            ),
        ),
    ]
