# Generated by Django 5.2.10 on 2026-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferences",
            name="notify_monthly_report",
            field=models.BooleanField(
                default=True, verbose_name="Monthly owner report"
            ),
        ),
    ]
