# Generated by Django 5.2.10 on 2026-07-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_preferences_notify_monthly_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferences",
            name="reply_auto_suggest",
            field=models.BooleanField(
                default=True,
                help_text="Draft AI replies automatically for new reviews (Pro plans).",
                verbose_name="Pre-generate reply drafts",
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="reply_language",
            field=models.CharField(
                default="en", max_length=8, verbose_name="Default reply language"
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="reply_signature",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Reply signature"
            ),
        ),
        migrations.AddField(
            model_name="preferences",
            name="reply_tone",
            field=models.CharField(
                default="warm",
                help_text="professional | warm | concise | playful",
                max_length=16,
                verbose_name="Default reply tone",
            ),
        ),
    ]
