# Generated by Django 5.2.10 on 2026-03-06 23:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("product_id", models.UUIDField(verbose_name="Product ID")),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Product Name"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                ("unit_price", models.IntegerField(verbose_name="Unit Price")),
                (
                    "date_added",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Added"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Payment ID",
                    ),
                ),
                ("subtotal", models.IntegerField(verbose_name="Subtotal")),
                ("tax", models.IntegerField(default=0, verbose_name="Tax")),
                ("discount", models.IntegerField(default=0, verbose_name="Discount")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Is Cancelled"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("product_id", models.UUIDField(verbose_name="Product ID")),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Product Name"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                ("price", models.IntegerField(verbose_name="Price")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("UNPAID", "Unpaid"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("MONTH", "Month"), ("YEAR", "Year")],
                        default="MONTH",
                        max_length=20,
                        verbose_name="Interval",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="Price")),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Current Period End"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="End At"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
