# Generated by Django 5.2.10 on 2026-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("reviews", "Reviews"),
                            ("rates", "Rates"),
                            ("calendar", "Calendar"),
                            ("analytics", "Analytics"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_record_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sync status",
                "verbose_name_plural": "Sync statuses",
            },
        ),
    ]
